app: ds-repo-template
env: staging
namespace: staging

chart:
  name: https://github.com/raffle-ai/onechart.git?sha=476907dda8238db3f1c24dfea6c6c43f5267e2c0&path=/charts/onechart/

values:
  image:
    repository: raffle.azurecr.io/ds-repo-template
    tag: "{{ .CIRCLE_TAG }}"
    pullPolicy: Always

  replicas: 1
  containerPort: 8080

  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      cpu: 500m
      memory: 500Mi

  gitRepository: raffle-ai/ds-repo-template
  gitSha: "{{ .CIRCLE_SHA1 }}"

  podAnnotations:
    config.linkerd.io/skip-outbound-ports: 5432,6379,4222

  probe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 10
    path: /
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3
