app: ds-repo-template
env: staging
namespace: staging
chart:
  name: https://github.com/raffle-ai/onechart.git?sha=d274740273cf37afd70d56a097d94e2c6d4d4640&path=/charts/onechart/
values:
  image:
    repository: raffle.azurecr.io/ds-repo-template
    tag: "{{ .CIRCLE_TAG }}"
    pullPolicy: Always
  replicas: 1
  containerPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      cpu: 500m
      memory: 500Mi
  gitRepository: raffle-ai/ds-repo-template
  gitSha: "{{ .CIRCLE_SHA1 }}"
  natsCerts: true
  podAnnotations:
    config.linkerd.io/skip-outbound-ports: 5432,6379,4222
  probe:
    enabled: true
    failureThreshold: 5
    initialDelaySeconds: 10
    path: /
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3
