version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  gimlet: "gimlet-io/circleci-orb@4.0.0"

workflows:
  build:
    jobs:
      - test:
          context:
            - AzureCR
            - Slack
            - DSGithub

      - bump_version:
          context:
            - DSGithub
            - AzureCR

          requires:
            - test

          filters:
            branches:
              only:
                - main

      - build_docker_prod_image:
          context:
            - AzureCR
            - Slack
            - DSGithub

          filters:
            branches:
              ignore: /.*/

            tags:
              only: /^v.*/

      - gimlet/gimlet-artifact-push:
          name: Notifying Gimlet about new version
          context:
            - Gimlet
            - Slack

          requires:
            - build_docker_prod_image

          filters:
            branches:
              ignore: /.*/

            tags:
              only: /^v.*/
jobs:
  test:
    docker:
      - image: raffle.azurecr.io/cimg-python:latest
        auth:
          username: $CLIENT_ID
          password: $CLIENT_SECRET

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Install dependency packages
          command: |
           git config --global url."https://${GIT_TOKEN}@github.com/".insteadOf "https://github.com/"
           poetry install

      - run:
          name: Lint
          command: |
            make lint

      - run:
          name: Test
          command: |
            make test

      - run:
          name: Build docker
          command: |
            make docker

      - slack/status:
          fail_only: true
          only_for_branches: main
          channel: tech-data-science-alerts

  bump_version:
    docker:
      - image: raffle.azurecr.io/cimg-python:latest
        auth:
          username: $CLIENT_ID
          password: $CLIENT_SECRET

    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Bump version
          command: |
            git config --global user.email "hal9000@raffle.ai"
            git config --global user.name "Hal 9000"
            git remote set-url origin https://$GIT_TOKEN@github.com/raffle-ai/ds-repo-template.git/

            python3 -m venv venv
            source venv/bin/activate
            pip install commitizen
            cz bump --changelog

            git push origin main
            git push origin --tags

  build_docker_prod_image:
    docker:
      - image: raffle.azurecr.io/cimg-python:latest
        auth:
          username: $CLIENT_ID
          password: $CLIENT_SECRET

    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Build docker
          command: |
            make docker-prod

      - run:
          name: Push docker
          command: |
            make docker-prod-push

      - slack/status:
          fail_only: true
          only_for_branches: main

